version: "3.9"

networks:
  app-tier:
    driver: bridge

services:
  rtsp_server:
    container_name: rtsp_server
    image: aler9/rtsp-simple-server:latest
    ports:
      - "8554:8554" # RTSP
      - "1935:1935" # RTMP
    restart: always
    networks:
      - app-tier

  gstreamer:
    container_name: gstreamer
    restart: no
    user: root
    build:
      context: .
    depends_on:
      - rtsp_server
    # ports:
    #   - "80:8000"
    # volumes:
    #   - ${PATH_IMAGE_CAPTURED}:/app/src/storage:rw
    # links:
    #   - "rabbit"
    environment:
      VIDEO=rtsp://172.22.0.2:8554/mystream
    networks:
      - app-tier

    stdin_open: true  # docker run -i
    tty: true         # docker run -t
    # command: ["bash"]
